{% set version = '0.0.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-funspotr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/funspotr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/funspotr/funspotr_{{ version }}.tar.gz
  sha256: 02562e7bb828dac2cfb3750af7fcaa101b3a4b06d9af2c86b2d7b6b0e73c8358

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-callr
    - r-dplyr >=0.8.3
    - r-formatr
    - r-fs
    - r-glue
    - r-here
    - r-httr
    - r-import >=1.3.0
    - r-knitr
    - r-lifecycle
    - r-purrr
    - r-readr
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-callr
    - r-dplyr >=0.8.3
    - r-formatr
    - r-fs
    - r-glue
    - r-here
    - r-httr
    - r-import >=1.3.0
    - r-knitr
    - r-lifecycle
    - r-purrr
    - r-readr
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('funspotr')"           # [not win]
    - "\"%R%\" -e \"library('funspotr')\""  # [win]

about:
  home: https://brshallo.github.io/funspotr/
  license: MIT
  summary: Helpers for parsing out the R functions and packages used in R scripts and notebooks.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: funspotr
# Title: Spot R Functions & Packages
# Version: 0.0.4
# Authors@R: person(given = "Bryan", family = "Shalloway", role = c("aut", "cre"), email = "brshallodev@gmail.com")
# Description: Helpers for parsing out the R functions and packages used in R scripts and notebooks.
# License: MIT + file LICENSE
# BugReports: https://github.com/brshallo/funspotr/issues
# Imports: dplyr (>= 0.8.3), tidyr, purrr, stringr, glue, knitr, httr, callr, readr, here, formatR, fs, tibble, utils, import (>= 1.3.0), lifecycle
# Suggests: remotes, visNetwork, igraph
# Enhances: blogdown
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# URL: https://brshallo.github.io/funspotr/
# Language: en-US
# NeedsCompilation: no
# Packaged: 2023-11-22 00:07:46 UTC; bshallow
# Author: Bryan Shalloway [aut, cre]
# Maintainer: Bryan Shalloway <brshallodev@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-11-22 00:20:02 UTC
